<fieldset ng-class="creare-info">
<table>
		<tr>
		<td><img src="//linkedretail.com/images/linkedretail_logo_320x132_updated.png" alt="SOCIALSEO" /></td>
			<td width="10"></td><td>
			<h3>SOCIALSEO version <?php echo $this->getModuleVersion() ?></h3>
				<p><strong><a href="mailto:support@linkedretail.com" target="_blank">Support</a></strong> - login on our website and use our help desk
				<br /><strong><a href="http://www.linkedretail.com" target="_blank">SEO</a></strong> - for more about our SEO services, visit our website and get in touch
				<br /><strong><a href="http://magento.narrativecard.com" target="_blank">How To</a></strong> - read our official blog post for our how-to video
				<br /><strong><a target="_blank" href="https://developers.facebook.com/tools/debug/og/object/">Test to see your link on Facebook</a></strong> - entering the product link to see how it will be displayed on Facebook</p>
			</td>
		</tr>
	</table>
</fieldset>